robotRTB: Plan
Plan
Functions
RTBvector lucciPLAN_givedir (RTBvector dest, RTBvector actual)
Plan calculate new direction.
RTBvector lucciPLAN_givedir_multiparam (RTB_FLOAT_TYPE actualx, RTB_FLOAT_TYPE actualy, RTB_FLOAT_TYPE destx, RTB_FLOAT_TYPE desty)
Plan calculate new direction (4 param version.
Function Documentation
RTBvector lucciPLAN_givedir (RTBvector dest, RTBvector actual)
Plan calculate new direction.
Calculates the direction towards the next waypoint given the actual position.
Parameters:
dest RTBvector with the destination vector
actual RTBvector with the actual position vector
Returns:
direction RTBvector containing the computed new direction
Definition at line 4 of file lucciPLAN.c.
References RTBvector::angle_deg_north, RTBvector::angle_rad, lucciSERVICE_rad2degnorth(), lucciSERVICE_vect_normalize(), lucciSERVICE_vect_set_norm(), RTB_FLOAT_TYPE, RTBvector::x, and RTBvector::y.
Referenced by lucciPLAN_givedir_multiparam().
{
    RTBvector localvec;
    RTB_FLOAT_TYPE localx, localy;
    localx = dest.x - actual.x;
    localy = dest.y - actual.y;
    localvec.angle_rad = atan2(localy, localx);
    localvec.angle_deg_north = lucciSERVICE_rad2degnorth(localvec.angle_rad);
    localvec.x = cos(localvec.angle_rad);
    localvec.y = sin(localvec.angle_rad);
    localvec = lucciSERVICE_vect_normalize(localvec);
    localvec = lucciSERVICE_vect_set_norm(2.0, localvec);
    return localvec;
}
RTBvector lucciPLAN_givedir_multiparam (RTB_FLOAT_TYPE actualx, RTB_FLOAT_TYPE actualy, RTB_FLOAT_TYPE destx, RTB_FLOAT_TYPE desty)
Plan calculate new direction (4 param version.
Calculates the direction towards the next waypoint given the actual position.
Parameters:
actualx RTBvector with the actual position X component
actualy RTBvector with the actual position Y component
destx RTBvector with the destination X component
desty RTBvector with the destination Y component
Returns:
direction RTBvector containing the computed new direction
Definition at line 19 of file lucciPLAN.c.
References lucciPLAN_givedir(), RTBvector::x, and RTBvector::y.
Referenced by RTB_update().
{
    RTBvector actual, dest;
    actual.x=actualx;
    actual.y=actualy;
    dest.x=destx;
    dest.y=desty;
    return lucciPLAN_givedir(dest,actual);
}