robotRTB: /home/erupter/Apps/netbeans_apps/LagalaRTB-V2/service.h File Reference
/home/erupter/Apps/netbeans_apps/LagalaRTB-V2/service.h File Reference
#include "output.h"
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <stdio.h>
#include "player_manager.h"
#include "options.h"
#include "cli_parser.h"
#include <omp.h>
#include "time_decimator.h"
Functions
static void s_signal_handler (int signal_value)
static void s_catch_signals (void)
Variables
volatile sig_atomic_t s_interrupted = 0
volatile sig_atomic_t alarm_expired = 0
Function Documentation
static void s_catch_signals (void) [static]
Definition at line 46 of file service.h.
References s_signal_handler().
Referenced by main().
{
    struct sigaction action;
    action.sa_handler = s_signal_handler;
    action.sa_flags = 0;
    sigemptyset (&action.sa_mask);
    sigaction (SIGINT, &action, NULL);
    sigaction (SIGTERM, &action, NULL);
    sigaction (SIGALRM, &action, NULL);
}
static void s_signal_handler (int signal_value) [static]
Definition at line 37 of file service.h.
Referenced by s_catch_signals().
{
    if (signal_value == SIGTERM || signal_value == SIGSTOP || signal_value == SIGINT)
        s_interrupted = 1;
    if (signal_value == SIGALRM)
        //signal(SIGALRM,alarm_wakeup);
        alarm_expired = 1;
}
Variable Documentation
volatile sig_atomic_t alarm_expired = 0
Definition at line 34 of file service.h.
volatile sig_atomic_t s_interrupted = 0
Definition at line 33 of file service.h.
Referenced by main().