#!/bin/bash
LIBNAME="lms511tcp"
FILENAME="lms511_tcp"

rm *.o
arm-linux-gnueabihf-gcc -Wall -c "$FILENAME".c -I../../Include
ar -cvq libbgl"$LIBNAME"hf.a "$FILENAME".o
mv libbgl"$LIBNAME"hf.a ../../Lib
