robotRTB: ObstacleAvoidance
ObstacleAvoidance
Defines
#define PI 3.14159265
Custom PI definition.
#define OA_ACTIVE_DISTANCE 7.0
Active distance.
#define OA_GRID_RADIAL_SAMPLING 5
Grid radial sampling.
#define OA_SENSOR_RESOLUTION 0.004363323
Sensor resolution.
#define OA_SENSOR_CENTER 0.0
Sensor center.
#define OA_SENSOR_COUNT 1080
Sensor count.
#define OA_WINDOW_THRESHOLD 5
Window Threshold.
#define OA_WINDOW_SIZE 5
Window Size.
#define OA_SENSOR_ORIENTATION OA_SENSOR_CLOCKWISE
Laser sensor data sequence (CW/CCW)
#define OA_SPEED_MAX 2.0
Maximum Speed.
#define OA_SPEED_MIN 0.1
Minimum Speed.
#define OA_SPEED_MODERATION_DIST 3.0
Speed moderation active distance.
#define OA_SAFETY_DISTANCE 1.0
Safety distance.
#define OA_AVOID_INTENSITY 2.0
Avoiding Intensity.
#define DEBUG 0
Debug define. Set to 1 to enable.
#define SIMUL 0
Simulator define. Set to 1 to enable.This requires Player 3 and Stage 4 to be installed on the system.
Functions
void OA_init (void)
OA Init.
RTBvector OA_perform_avoidance (RTB_FLOAT_TYPE readings[], long count, RTBvector yaw, RTBvector desired_heading)
Perform avoidance.
Define Documentation
#define OA_ACTIVE_DISTANCE 7.0
Active distance.
Meters. Distance at which the obstacle avoidance becomes active.
Definition at line 41 of file lucciOA.h.
Referenced by OA_perform_avoidance().
#define OA_AVOID_INTENSITY 2.0
Avoiding Intensity.
Adimensional multiplier used to tweak how the algorithm performs. The base calculation remains the same, this value just allows to augment the strength of the algorithm's response allowing for a stronger repulsion.
Definition at line 137 of file lucciOA.h.
Referenced by OA_perform_avoidance().
#define OA_GRID_RADIAL_SAMPLING 5
Grid radial sampling.
Adimensional. Maximum intensity of the detected occupation of the sector to allow attempting to consider the direction viable.
Definition at line 49 of file lucciOA.h.
Referenced by OA_init(), and OA_perform_avoidance().
#define OA_SAFETY_DISTANCE 1.0
Safety distance.
Minimum DO-NOT-CROSS distance from any obstacle: should this value be approached forward speed will diminish until it get nullified.
Definition at line 128 of file lucciOA.h.
Referenced by OA_perform_avoidance().
#define OA_SENSOR_CENTER 0.0
Sensor center.
In radians. The center of the laser readings relative to the rover. If a 180° FOV laser is used, than most probably this is 0.
Definition at line 66 of file lucciOA.h.
Referenced by OA_init(), and OA_perform_avoidance().
#define OA_SENSOR_COUNT 1080
Sensor count.
Number of readings the laser outputs.
Definition at line 74 of file lucciOA.h.
Referenced by OA_init().
#define OA_SENSOR_ORIENTATION OA_SENSOR_CLOCKWISE
Laser sensor data sequence (CW/CCW)
Set to reflect how the laser scanner reports its data: CW (human) or CCW (mathematical)
Definition at line 98 of file lucciOA.h.
#define OA_SENSOR_RESOLUTION 0.004363323
Sensor resolution.
Radians. Incremental radial distance between consecutive laser samples.
Definition at line 57 of file lucciOA.h.
Referenced by OA_init(), and OA_perform_avoidance().
#define OA_SPEED_MAX 2.0
Maximum Speed.
Maximum speed the OA algorithm will attempt to attain. In m/s.
Definition at line 106 of file lucciOA.h.
#define OA_SPEED_MIN 0.1
Minimum Speed.
Minimum speed the OA algorithm will attempt to attain. In m/s.
Definition at line 113 of file lucciOA.h.
#define OA_SPEED_MODERATION_DIST 3.0
Speed moderation active distance.
The distance from any detected obstacle at which the algorithm will start moderating speed.
Definition at line 120 of file lucciOA.h.
#define OA_WINDOW_SIZE 5
Window Size.
Adimensional. Number of sequencial radial sectors that must be free to consider that a viable direction.
Definition at line 90 of file lucciOA.h.
Referenced by OA_perform_avoidance().
#define OA_WINDOW_THRESHOLD 5
Window Threshold.
Adimensional. Maximum intensity of the detected occupation of the sector to allow attempting to consider the direction viable.
Definition at line 82 of file lucciOA.h.
Referenced by OA_perform_avoidance().
Function Documentation
void OA_init (void)
OA Init.
Initializes the algorithm. Mandatory execution before calling its functions.
Definition at line 26 of file lucciOA.c.
References OA_GRID_RADIAL_SAMPLING, OA_SENSOR_CENTER, OA_SENSOR_COUNT, and OA_SENSOR_RESOLUTION.
{
    long i,j;
    /*OA_map_size = 2* OA_ACTIVE_DISTANCE / OA_GRID_RESOLUTION;
    OA_map = malloc(OA_map_size * sizeof(unsigned int*));
    for (i=0; i<OA_map_size; i++)
        OA_map[i] = malloc(OA_map_size * sizeof(unsigned int));
    for (i=0;i<OA_map_size; i++)
        for (j=0; j<OA_map_size; j++)
        {
            OA_map[i][j]=0;
        }*/
    OA_internal_min_angle = OA_SENSOR_CENTER - OA_SENSOR_COUNT/2 * OA_SENSOR_RESOLUTION;
    OA_radial_size = (int)(360 / OA_GRID_RADIAL_SAMPLING);
    //OA_radial_map = (unsigned int *) malloc (OA_radial_size * sizeof(unsigned int));
    OA_radial_map = (OA_radial_map_t *) malloc (OA_radial_size * sizeof(OA_radial_map_t));
    for (i=0;i<OA_radial_size;i++)
    {
        OA_radial_map[i].intensity=0;
        OA_radial_map[i].validity=0;
    }
        //OA_radial_map[i]=0;
    OA_inited = 1;
}
RTBvector OA_perform_avoidance (RTB_FLOAT_TYPE readings[], long count, RTBvector yaw, RTBvector desired_heading)
Perform avoidance.
This function must be periodically called to guarantee correct recording of positions. It is designed to be integrated in a superloop. If the module is disabled, calling this function won't affect performance, as no operations will be performed in such a case (the module will check its state and immediately return).
Parameters:
readings vector of RTB_FLOAT_TYPE values carrying the laser readings
count long variable containing the number of laser readings in a vector
yaw RTBvector containing the current yaw (true north) of the vehicle
desired_heading RTBvector containing the desired heading
Returns:
an RTBvector with the actual commands (heading, speed)
See also:
RTBvector
Definition at line 67 of file lucciOA.c.
References RTBvector::angle_deg_north, RTBvector::angle_rad, RTB_status::control_vector, lucciSERVICE_deg_adjust(), lucciSERVICE_degnorth2rad(), lucciSERVICE_rad_adjust(), lucciSERVICE_vect_normalize(), lucciSERVICE_vect_set_norm(), lucciSERVICE_vect_sum(), RTBvector::norm, OA_ACTIVE_DISTANCE, OA_AVOID_INTENSITY, OA_GRID_RADIAL_SAMPLING, OA_SAFETY_DISTANCE, OA_SENSOR_CENTER, OA_SENSOR_RESOLUTION, OA_WINDOW_SIZE, OA_WINDOW_THRESHOLD, PI, RTB_FLOAT_TYPE, RTBvector::x, and RTBvector::y.
{
    RTBvector localvec,localvec2;
    if (OA_inited == 0)
    {
        localvec.x=0;
        localvec.y=0;
        localvec.norm=0;
        localvec.angle_deg_north=0;
        localvec.angle_rad=M_PI_2;
        return localvec;
    }
    RTB_FLOAT_TYPE angle, min_distance=50;
    long i,j;
    long index,angle_int;
    int left_reached_end = 0, left_valid = 0, right_reached_end = 0, right_valid = 0;
    OA_internal_map_update();
    //Range points discretization and mapping
    for (i=0; i<count; i++)
    {
        if (readings[i] < OA_ACTIVE_DISTANCE)
        {
#if (OA_SENSOR_ORIENTATION == OA_SENSOR_CLOCKWISE)
            angle = OA_SENSOR_CENTER + OA_internal_min_angle + (i*OA_SENSOR_RESOLUTION);
            //x=cos(yaw+OA_SENSOR_CENTER+(i*OA_SENSOR_RESOLUTION))*readings[i];
            //y=sin(yaw+OA_SENSOR_CENTER+(i*OA_SENSOR_RESOLUTION))*readings[i];
#elif (OA_SENSOR_ORIENTATION == OA_SENSOR_ANTI_CLOCKWISE)
            angle = yaw + OA_SENSOR_CENTER - OA_internal_min_angle - (i*OA_SENSOR_RESOLUTION);
            //x=cos(yaw+OA_SENSOR_CENTER+((count-i)*OA_SENSOR_RESOLUTION))*readings[count-i];
            //y=sin(yaw+OA_SENSOR_CENTER+((count-i)*OA_SENSOR_RESOLUTION))*readings[count-i];
#endif
            angle = lucciSERVICE_rad_adjust(angle);
            if ((angle < M_PI_2) && (angle > -M_PI_2))
                min_distance = MIN(min_distance, readings[i]);
            angle = lucciSERVICE_rad_adjust(angle+yaw.angle_rad);
            angle_int = 900-floor(angle/PI*1800);
            if (angle_int > 3600)
            {
                angle_int=-3600+angle_int;
            }
            if (angle_int < 0)
            {
                angle_int=3600+angle_int;
            }
            /*angle_int=-angle_int+900;
            if (angle_int < 0)
                angle_int += 3600;
            if (angle_int > 3600)
                angle_int -= 3600;*/
            index = (long)floor(angle_int/(10*OA_GRID_RADIAL_SAMPLING));
            OA_radial_map[index].intensity++;
            /*if (abs(x) < OA_ACTIVE_DISTANCE && abs(y) < OA_ACTIVE_DISTANCE)
            {
                x=floor((x+OA_ACTIVE_DISTANCE) / OA_GRID_RESOLUTION);
                y=floor((y+OA_ACTIVE_DISTANCE) / OA_GRID_RESOLUTION);
                OA_map[(long)x][(long)y]++;
            }*/
        }
    }
    long _validity_count=0;
    for (i=0;i<OA_radial_size;i++)
    {
        if (OA_radial_map[i].intensity<OA_WINDOW_THRESHOLD)
        {
            _validity_count++;
        }
        else
            _validity_count=0;
        if (_validity_count == OA_WINDOW_SIZE)
        {
            OA_radial_map[i].validity = 1;
            long j;
            for (j=0;j<_validity_count-1;j++)
                OA_radial_map[i-_validity_count+j+1].validity=1;
        }
        if (_validity_count > OA_WINDOW_SIZE)
            OA_radial_map[i].validity = 1;
    }
#if (DEBUG == 1)
    //Radial discretization of the map
    output_pty = fopen("/home/erupter/data.csv","w+");
    //fprintf(output_pty,"START,");
    for (i=0;i<OA_radial_size-1;i++)
    {
        fprintf(output_pty,"%03d,",OA_radial_map[i].intensity);
    }
    fprintf(output_pty,"%03d\n",OA_radial_map[OA_radial_size].validity);
    for (i=0;i<OA_radial_size-1;i++)
    {
        fprintf(output_pty,"%03d,",OA_radial_map[i].validity);
    }
#endif
//    len=sprintf(mystr,"START,");
//    write(output_pty,mystr,len);
//
//    for (i=0;i<OA_radial_size-1;i++)
//    {
//        len=sprintf(mystr,"%03d,",OA_radial_map[i].intensity);
//        write(output_pty,mystr,len);
//    }
//    len=sprintf(mystr,"%03d,END\n\r",OA_radial_map[OA_radial_size].intensity);
//    write(output_pty,mystr,len);
    fclose(output_pty);
    index = (long)floor(desired_heading.angle_deg_north/(OA_GRID_RADIAL_SAMPLING));
    if (OA_radial_map[index].validity != 1)
    {
        long count_left=0, count_right=0, result;
        while((OA_radial_map[index-count_left].validity==0 && OA_radial_map[index+count_right].validity==0) && index-count_left>0 && index+count_right<OA_radial_size)
        {
            count_left++;
            count_right++;
        }
        if (index-count_left == 0)
            left_reached_end = 1;
        else
            if (OA_radial_map[index-count_left].validity == 1)
                left_valid = 1;
        if (index+count_right >= OA_radial_size)
            right_reached_end = 1;
        else
            if (OA_radial_map[index+count_right].validity == 1)
                right_valid = 1;
        if (!right_valid && !left_valid )
        {
            if (left_reached_end)
            {
                int temp=count_left;
                while ((OA_radial_map[OA_radial_size-count_left+temp].validity==0 && OA_radial_map[index+count_right].validity==0) && index+count_right < OA_radial_size)
                {
                    count_right++;
                    count_left++;
                }
                if (OA_radial_map[OA_radial_size-count_left+temp].validity == 1)
                    left_valid = 1;
                if (OA_radial_map[index+count_right].validity == 1)
                    right_valid = 1;
            }
            else
            {
                int temp=count_right;
                while (OA_radial_map[index-count_left].validity==0 && OA_radial_map[count_right-temp].validity == 0 && index-count_left < OA_radial_size)
                {
                    count_left++;
                    count_right++;
                }
                if (OA_radial_map[index-count_left].validity == 1)
                    left_valid = 1;
                if (OA_radial_map[count_right-temp].validity == 1)
                    right_valid = 1;
            }
        }
        if (left_valid)
        {
            if (left_reached_end)
            {
                angle = lucciSERVICE_degnorth2rad(lucciSERVICE_deg_adjust((RTB_FLOAT_TYPE) 5 * (OA_radial_size+index-count_left) - 20));
            }
            else
            {
                angle = lucciSERVICE_degnorth2rad(lucciSERVICE_deg_adjust((RTB_FLOAT_TYPE) 5 * (index-count_left) - 20));
            }
        }
        else
        {
            if (right_valid)
                if (right_reached_end)
                {
                    angle = lucciSERVICE_degnorth2rad(lucciSERVICE_deg_adjust((RTB_FLOAT_TYPE) 5 * (index + count_right - OA_radial_size) + 20));
                }
                else
                {
                    angle = lucciSERVICE_degnorth2rad(lucciSERVICE_deg_adjust((RTB_FLOAT_TYPE) 5 * (index + count_right) + 20));
                }
        }
        /*result = MIN(count_left,count_right);
        if (count_left > 0)
            if (OA_radial_map[index-count_left].validity == 1)
                control_values.heading = (RTB_FLOAT_TYPE)((index * 5) - 5 * (count_left+1));
        if (result == count_right)
            control_values.heading = (RTB_FLOAT_TYPE)((index * 5) + 5 * (count_right+1));
        if (control_values.heading < 0)
            control_values.heading += 360;
        if (control_values.heading > 360)
            control_values.heading -= 360;*/
        localvec.x = cos(angle);
        localvec.y = sin(angle);
        localvec = lucciSERVICE_vect_normalize(localvec);
    }
    else
        localvec = desired_heading;
    //localvec = lucciSERVICE_vect_set_norm(OA_SPEED_MAX, localvec);
    //emergency avoid
    if (min_distance < OA_SPEED_MODERATION_DIST && localvec.norm > 0.0)
    {
        for (i=0; i<count; i++)
        {
            min_distance = MIN(min_distance,readings[i]);
            if (readings[i] == min_distance)
                index = i;
        }
#if (OA_SENSOR_ORIENTATION == OA_SENSOR_CLOCKWISE)
        angle = yaw.angle_rad + OA_SENSOR_CENTER + OA_internal_min_angle + (index*OA_SENSOR_RESOLUTION);
#elif (OA_SENSOR_ORIENTATION == OA_SENSOR_ANTI_CLOCKWISE)
        angle = yaw.angle_rad + OA_SENSOR_CENTER - OA_internal_min_angle - (i*OA_SENSOR_RESOLUTION);
#endif
        angle = lucciSERVICE_rad_adjust(angle + M_PI);
        localvec2.x = cos (angle);
        localvec2.y = sin (angle);
        localvec = lucciSERVICE_vect_sum(localvec, localvec2);
        //localvec = lucciSERVICE_vect_set_norm(OA_AVOID_INTENSITY * (1 - min_distance / OA_SPEED_MODERATION_DIST),localvec);
        localvec = lucciSERVICE_vect_set_norm(MIN(2,min_distance / OA_AVOID_INTENSITY),localvec);
        RTBstatus.control_vector = localvec;
        avoid_soft = 1;
    }
    if (min_distance < OA_SAFETY_DISTANCE)
        localvec = lucciSERVICE_vect_set_norm(0.01, localvec);
    return localvec;
}