robotRTB: Service
Service
Data Structures
struct RTBvehicle_control
RTBvehicle_control.
struct RTBvector
Vector type.
struct RTB_status
RTB main status structure.
Defines
#define RTB_FLOAT_TYPE double
RTB float type mask definition.
Typedefs
typedef struct RTB_status RTB_status
RTB main status structure.
Enumerations
enum RTB_mode { RTB_idle = 0, RTB_recording, RTB_tracking, RTB_pause }
RTB operating main mode enumeration.
Functions
RTB_FLOAT_TYPE lucciSERVICE_rad2degnorth (RTB_FLOAT_TYPE angle)
Radians to Degrees North.
RTB_FLOAT_TYPE lucciSERVICE_degnorth2rad (RTB_FLOAT_TYPE angle)
Degrees North to Radians.
RTB_FLOAT_TYPE lucciSERVICE_rad_adjust (RTB_FLOAT_TYPE angle)
Radians adjust.
RTB_FLOAT_TYPE lucciSERVICE_deg_adjust (RTB_FLOAT_TYPE angle)
Degrees adjust.
RTBvector lucciSERVICE_vect_normalize (RTBvector data)
Vector normalize.
RTBvector lucciSERVICE_vect_sum (RTBvector a, RTBvector b)
Vector sumPerforms the sum between two vectors. Emphasis is on the X/Y values, norm and angles are calculated afterwards. Thus summing vectors with missing X/Y values will result in undefined behaviour.
RTBvector lucciSERVICE_vect_set_norm (RTB_FLOAT_TYPE norm, RTBvector vect)
Vector set norm.
Define Documentation
#define RTB_FLOAT_TYPE double
RTB float type mask definition.
To make the software as much platform agnostic as possible, this definition allows for custom remapping of the float type to whatever deemed fit. Even integer types could be used, but this would surely cause problems with the mathematical operations involved.
Definition at line 27 of file lucciSERVICE.h.
Referenced by lucciPLAN_givedir(), lucciSERVICE_vect_normalize(), lucciSERVICE_vect_set_norm(), OA_perform_avoidance(), and RTB_update().
Typedef Documentation
typedef struct RTB_status RTB_status
RTB main status structure.
Contains status informations concerning the module, as well as the last instructions issued to the system to reach the origin.
Parameters:
mode an RTB_mode object depicting the state of the module
complete a Boolean notifying of the completition of the assignment
control_values
distance a RTB_FLOAT_TYPE containing the distance to the origin, a value of -1 means N/A
control_vector
Enumeration Type Documentation
enum RTB_mode
RTB operating main mode enumeration.
Values used to control the behavior of the module.
See also:
RTB_set_mode
Enumerator:
RTB_idle
Default state upon initialization, no activity.
RTB_recording
Active state, positions are recorded.
RTB_tracking
Active state, cached positions are used to guide the vehicle.
RTB_pause
Paused state, cache is retained, no new positions are addes.
Definition at line 65 of file lucciSERVICE.h.
             {
    RTB_idle = 0,
    RTB_recording,
    RTB_tracking,
    RTB_pause
}RTB_mode;
Function Documentation
RTB_FLOAT_TYPE lucciSERVICE_deg_adjust (RTB_FLOAT_TYPE angle)
Degrees adjust.
Performs a sanity check on an angle in degrees. Meaning it can't be less then 0° or higher than 359.9° (precision is up to the underlying value type)
Parameters:
angle RTB_FLOAT_TYPE carrying the value to be modified
Definition at line 22 of file lucciSERVICE.c.
Referenced by lucciSERVICE_rad2degnorth(), and OA_perform_avoidance().
{
    if (angle < 0)
        angle += 360;
    if (angle > 360)
        angle -= 360;
    return angle;
}
RTB_FLOAT_TYPE lucciSERVICE_degnorth2rad (RTB_FLOAT_TYPE angle)
Degrees North to Radians.
Converts a value in degrees true north to radians.
Parameters:
angle RTB_FLOAT_TYPE carrying the value to be modified
Definition at line 8 of file lucciSERVICE.c.
References lucciSERVICE_rad_adjust().
Referenced by OA_perform_avoidance().
{
    return lucciSERVICE_rad_adjust((90-angle)/180*M_PI);
}
RTB_FLOAT_TYPE lucciSERVICE_rad2degnorth (RTB_FLOAT_TYPE angle)
Radians to Degrees North.
* Converts a value in radians to degrees true north.
Parameters:
angle RTB_FLOAT_TYPE carrying the value to be modified
Definition at line 3 of file lucciSERVICE.c.
References lucciSERVICE_deg_adjust().
Referenced by lucciPLAN_givedir(), lucciSERVICE_vect_normalize(), and lucciSERVICE_vect_sum().
{
    return lucciSERVICE_deg_adjust(90-(angle/M_PI * 180));
}
RTB_FLOAT_TYPE lucciSERVICE_rad_adjust (RTB_FLOAT_TYPE angle)
Radians adjust.
Performs a sanity check on an angle in radians. Meaning it can't be less then -PI/2 or higher than +PI/2
Parameters:
angle RTB_FLOAT_TYPE carrying the value to be modified
Definition at line 13 of file lucciSERVICE.c.
Referenced by lucciSERVICE_degnorth2rad(), and OA_perform_avoidance().
{
    if(angle<M_PI)
        angle+=2*M_PI;
    if (angle > M_PI)
        angle-=2*M_PI;
    return angle;
}
RTBvector lucciSERVICE_vect_normalize (RTBvector data)
Vector normalize.
Useful after mathematical operations concerning X/Y values: recalculates the norm and makes the angle values coherent with the vector values.
Parameters:
data RTBvector carrying the value to be modified
Definition at line 31 of file lucciSERVICE.c.
References RTBvector::angle_deg_north, RTBvector::angle_rad, lucciSERVICE_rad2degnorth(), RTBvector::norm, RTB_FLOAT_TYPE, RTBvector::x, and RTBvector::y.
Referenced by lucciPLAN_givedir(), lucciSERVICE_vect_sum(), OA_perform_avoidance(), and RTB_update().
{
    RTB_FLOAT_TYPE accum;
    RTBvector local = data;
    accum = sqrt(pow(data.x,2)+pow(data.y,2));
    local.x = data.x/accum;
    local.y = data.y/accum;
    local.norm = sqrt(pow(local.x,2)+pow(local.y,2));
    local.angle_rad = atan2(local.y, local.x);
    local.angle_deg_north = lucciSERVICE_rad2degnorth(local.angle_rad);
    return local;
}
RTBvector lucciSERVICE_vect_set_norm (RTB_FLOAT_TYPE norm, RTBvector vect)
Vector set norm.
Arbitrarily set the norm of a vector. Useful to modify the speed should it be connected with the length of the vector. Vector value must be fully qualified: both X and Y together with current NORM must be coherent values. Angles get recalculated on the fly.
Parameters:
norm RTB_FLOAT_TYPE carrying the new norm
vect RTBvector carrying the vector to be modified
Definition at line 54 of file lucciSERVICE.c.
References RTBvector::norm, RTB_FLOAT_TYPE, RTBvector::x, and RTBvector::y.
Referenced by lucciPLAN_givedir(), OA_perform_avoidance(), and RTB_update().
{
    RTBvector local = vect;
    RTB_FLOAT_TYPE accum;
    if (vect.norm != 0)
    {
        accum = norm / vect.norm;
        local.x = vect.x * accum;
        local.y = vect.y * accum;
        local.norm = sqrt(pow(local.x,2)+pow(local.y,2));
    }
    return local;
}
RTBvector lucciSERVICE_vect_sum (RTBvector a, RTBvector b)
Vector sumPerforms the sum between two vectors. Emphasis is on the X/Y values, norm and angles are calculated afterwards. Thus summing vectors with missing X/Y values will result in undefined behaviour.
Parameters:
a RTBvector carrying operand A
b RTBvector carrying operand B
Definition at line 44 of file lucciSERVICE.c.
References RTBvector::angle_deg_north, RTBvector::angle_rad, lucciSERVICE_rad2degnorth(), lucciSERVICE_vect_normalize(), RTBvector::x, and RTBvector::y.
Referenced by OA_perform_avoidance().
{
    RTBvector local;
    local.x = a.x + b.x;
    local.y = a.y + b.y;
    local.angle_rad = atan2(local.y,local.x);
    local.angle_deg_north = lucciSERVICE_rad2degnorth(local.angle_rad);
    return lucciSERVICE_vect_normalize(local);
}