#!/bin/bash
SOURCE="/home/lucciu/beaglebone_code/Common/Source"
INCLUDE="/home/lucciu/beaglebone_code/Common/Include"

gcc -Wall $SOURCE/Segway/segway_server.c $SOURCE/Segway/segway_udp.c $SOURCE/Segway/segway_config.c -o segway_server.o -I$INCLUDE
