#!/bin/bash
SOURCE="/home/root/Common/Source"
INCLUDE="/home/root/Common/Include"

gcc -Wall $SOURCE/Segway/segway_server.c $SOURCE/Segway/segway_udp.c $SOURCE/Segway/segway_config.c -o segway_server.o -I$INCLUDE
