#!/bin/bash
LIBNAME="segwayudp"
FILENAME="segway_udp_v2"
FILENAME2="segway_config"

rm *.o
arm-linux-gnueabi-gcc -Wall -c "$FILENAME".c "$FILENAME2".c -I../../Include
ar -cvq libbgl"$LIBNAME".a "$FILENAME".o "$FILENAME2".o
mv libbgl"$LIBNAME".a ../../Lib
