#!/bin/bash
SOURCE="/home/lucciu/beaglebone_code/Common/Source"
INCLUDE="/home/lucciu/beaglebone_code/Common/Include"

gcc -Wall $SOURCE/Arm/arm_server.c $SOURCE/Socket_udp/socket_udp.c -o arm_server.o -I$INCLUDE
