#!/bin/bash
LIBNAME="armrs485"
FILENAME="arm_rs485"

rm *.o
arm-linux-gnueabihf-gcc -Wall -c "$FILENAME".c -I../../Include
ar -cvq libbgl"$LIBNAME"hf.a "$FILENAME".o
mv libbgl"$LIBNAME"hf.a ../../Lib

LIBNAME="armudp"
FILENAME="arm_udp"

arm-linux-gnueabihf-gcc -Wall -c "$FILENAME".c -I../../Include
ar -cvq libbgl"$LIBNAME"hf.a "$FILENAME".o
mv libbgl"$LIBNAME"hf.a ../../Lib
