#!/bin/bash
LIBNAME="armrs485"
FILENAME="arm_rs485"

rm *.o
arm-linux-gnueabi-gcc -Wall -c "$FILENAME".c -I../../Include
ar -cvq libbgl"$LIBNAME".a "$FILENAME".o
mv libbgl"$LIBNAME".a ../../Lib

LIBNAME="armudp"
FILENAME="arm_udp"

arm-linux-gnueabi-gcc -Wall -c "$FILENAME".c -I../../Include
ar -cvq libbgl"$LIBNAME".a "$FILENAME".o
mv libbgl"$LIBNAME".a ../../Lib
