#!/bin/bash
LIBNAME="kalman"
FILENAME="kalman"

rm *.o
arm-linux-gnueabi-gcc -Wall -c "$FILENAME".c -I../../Include -I../../../gsl-1.9
ar -cvq libbgl"$LIBNAME".a "$FILENAME".o
mv libbgl"$LIBNAME".a ../../Lib
