#!/bin/bash
LIBNAME="kalman"
FILENAME="kalman"

rm *.o
arm-linux-gnueabihf-gcc -Wall -c "$FILENAME".c -I../../Include -I../../../gsl-1.9
ar -cvq libbgl"$LIBNAME"hf.a "$FILENAME".o
mv libbgl"$LIBNAME"hf.a ../../Lib
